import test from "node:test";
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { buildCampaignGeographyPlan, classifyTarget, runCampaignGeographyBackfill, uuidV5, EXPECTED_LEVELS, CAMPAIGN_GEOGRAPHY_EXECUTION_CONFIRMATION, CAMPAIGN_GEOGRAPHY_CANONICAL_VERSION, MASTER_AREA_CHUNK_SIZE, ASSIGNMENT_CHUNK_SIZE, canonicalHash, parseBackfillCliArgs, assertSafeIdentity } from "../server/services/campaignGeographyBackfill.js";

function fixture(){
 const tenantId=randomUUID(),campaignId=randomUUID(),actorId=randomUUID();
 const levels=EXPECTED_LEVELS.map(([name,orderIndex])=>({id:randomUUID(),tenantId,name,orderIndex,isActive:true,createdAt:new Date("2026-01-01"),updatedAt:new Date("2026-01-02")}));
 const areas=[];let parent=null;for(const [i,[, ,count]] of EXPECTED_LEVELS.entries()){const current=[];for(let n=0;n<count;n++){const id=randomUUID();current.push({id,tenantId,campaignId,levelId:levels[i].id,parentId:i?parent[n%parent.length].id:null,name:`N-${i}-${n}`,code:`C-${i}-${n}`,isActive:true,sourceInstitution:"INEC",sourceDocument:"Dataset",sourceVersionDate:null,retrievalDate:new Date("2026-09-25"),importedAt:new Date("2026-09-26"),validationStatus:"VALIDATED",createdAt:new Date("2026-09-26"),updatedAt:new Date("2026-09-27")});}areas.push(...current);parent=current;}
 return{source:{levels,areas,country:"Nigeria"},actors:[{id:actorId}],tenantId,campaignId};
}
function prismaShape(target){return{levels:target.levels.map(x=>({...structuredClone(x)})),areas:target.areas.map(x=>({...structuredClone(x)})),assignments:target.assignments.map(x=>({...structuredClone(x),createdAt:new Date("2026-10-01"),updatedAt:new Date("2026-10-02"),removedAt:x.removedAt??null}))};}
function repoFor(f,{target={levels:[],areas:[],assignments:[]},failAreaChunk=0,failAssignmentChunk=0,failAudit=false}={}){const writes=[],txOperations=[];let current=prismaShape(target),areaCalls=0,assignmentCalls=0;const make=(inTransaction=false)=>({getIdentity:async()=>({database:"neondb",branchId:"br-test"}),readSource:async()=>{if(inTransaction)txOperations.push("readSource");return f.source},findEligibleActors:async()=>{if(inTransaction)txOperations.push("findEligibleActors");return f.actors},readTarget:async()=>{if(inTransaction)txOperations.push("readTarget");return current},acquireAdvisoryLock:async()=>{writes.push("lock");txOperations.push("lock")},insertMasterLevels:async d=>{writes.push("levels");txOperations.push("insertMasterLevels");current.levels=structuredClone(d)},insertMasterAreas:async d=>{areaCalls++;writes.push(`areas:${d.length}`);txOperations.push(`insertMasterAreas:${d.length}`);if(areaCalls===failAreaChunk)throw new Error("area chunk failure");current.areas.push(...structuredClone(d))},insertAssignments:async d=>{assignmentCalls++;writes.push(`assignments:${d.length}`);txOperations.push(`insertAssignments:${d.length}`);if(assignmentCalls===failAssignmentChunk)throw new Error("assignment chunk failure");current.assignments.push(...prismaShape({levels:[],areas:[],assignments:d}).assignments)},appendAudit:async()=>{writes.push("audit");txOperations.push("appendAudit");if(failAudit)throw new Error("audit failure")},transaction:async cb=>{const before=structuredClone(current);try{return await cb(make(true))}catch(e){current=before;throw e;}}});return{repository:make(),writes,txOperations,get target(){return current}};}
const expected={projectId:"project",branchId:"br-test",branchName:"test",database:"neondb"};

test("mapping preserves reviewed levels, provenance, null version dates and deterministic IDs",()=>{const f=fixture();const p=buildCampaignGeographyPlan(f.source,f.actors);const sourceIds=new Set(f.source.areas.map((x)=>x.id));assert.deepEqual(p.masterLevels.map(x=>x.orderIndex),[0,1,2,5,6]);assert.equal(p.masterAreas.length,9627);assert.ok(p.masterAreas.every((x)=>sourceIds.has(x.id)&&x.countryCode==="NG"&&x.sourceVersionDate===null));assert.equal(p.assignments[0].id,uuidV5(`${f.tenantId}\0${f.campaignId}\0${p.masterAreas[0].id}`));assert.notEqual(p.assignments[0].id,p.masterAreas[0].id);assert.equal(buildCampaignGeographyPlan(f.source,f.actors).evidence.assignments,p.evidence.assignments);});
test("dry-run validates everything and performs zero writes",async()=>{const f=fixture(),r=repoFor(f);const out=await runCampaignGeographyBackfill({repository:r.repository,expectedIdentity:expected});assert.equal(out.outcome,"DRY_RUN_VALID");assert.deepEqual(r.writes,[]);});
test("source integrity failures fail closed",()=>{for(const mutate of [f=>f.source.areas.pop(),f=>f.source.areas[1].parentId=null,f=>f.source.areas[1].parentId=f.source.areas[1].id,f=>f.source.areas[1].levelId=f.source.levels[4].id,f=>f.source.areas[2].code=f.source.areas[1].code,f=>{f.source.areas[2].name=f.source.areas[1].name;f.source.areas[2].parentId=f.source.areas[1].parentId;}]){const f=fixture();mutate(f);assert.throws(()=>buildCampaignGeographyPlan(f.source,f.actors));}});
test("actor resolution requires exactly one verified eligible actor result",()=>{const f=fixture();assert.throws(()=>buildCampaignGeographyPlan(f.source,[]),{code:"ACTOR_NOT_FOUND"});assert.throws(()=>buildCampaignGeographyPlan(f.source,[...f.actors,{id:randomUUID()}]),{code:"MULTIPLE_ACTORS"});});
test("target classifier normalizes real Prisma assignment rows and rejects partial/conflicting",()=>{const f=fixture(),p=buildCampaignGeographyPlan(f.source,f.actors),actual=prismaShape({levels:p.masterLevels,areas:p.masterAreas,assignments:p.assignments});assert.equal(classifyTarget({levels:[],areas:[],assignments:[]},p),"EMPTY");assert.equal(classifyTarget(actual,p),"ALREADY_COMPLETE");assert.throws(()=>classifyTarget({levels:p.masterLevels,areas:[],assignments:[]},p),{code:"PARTIAL_TARGET"});actual.assignments[0].isActive=false;assert.throws(()=>classifyTarget(actual,p),{code:"CONFLICTING_TARGET"});});
test("target state machine fails closed for isolated and partial target tables",()=>{const f=fixture(),p=buildCampaignGeographyPlan(f.source,f.actors);for(const target of [{levels:[],areas:p.masterAreas,assignments:[]},{levels:[],areas:[],assignments:p.assignments},{levels:p.masterLevels,areas:p.masterAreas,assignments:p.assignments.slice(0,-1)}])assert.throws(()=>classifyTarget(target,p),{code:"PARTIAL_TARGET"});});
test("complete-looking targets reject wrong parent, actor, campaign, and assignment UUID",()=>{const f=fixture(),p=buildCampaignGeographyPlan(f.source,f.actors),exact=prismaShape({levels:p.masterLevels,areas:p.masterAreas,assignments:p.assignments});const mutations=[target=>{target.areas[1].parentId=randomUUID()},target=>{target.assignments[0].createdById=randomUUID()},target=>{target.assignments[0].campaignId=randomUUID()},target=>{target.assignments[0].id=randomUUID()}];for(const mutate of mutations){const target=structuredClone(exact);mutate(target);assert.throws(()=>classifyTarget(target,p),{code:"CONFLICTING_TARGET"});}});
test("execution locks first, chunks writes, verifies Prisma-shaped target, and leaves legacy untouched",async()=>{const f=fixture(),before=structuredClone(f.source),r=repoFor(f);const out=await runCampaignGeographyBackfill({repository:r.repository,expectedIdentity:expected,mode:"execute",confirmation:CAMPAIGN_GEOGRAPHY_EXECUTION_CONFIRMATION,commit:"abc"});assert.equal(out.outcome,"EXECUTED");assert.equal(r.txOperations[0],"lock");assert.deepEqual(r.txOperations.slice(0,4),["lock","readSource","findEligibleActors","readTarget"]);const areaWrites=r.writes.filter(x=>x.startsWith("areas:")),assignmentWrites=r.writes.filter(x=>x.startsWith("assignments:"));assert.ok(areaWrites.every(x=>Number(x.split(":")[1])<=MASTER_AREA_CHUNK_SIZE));assert.equal(areaWrites.reduce((n,x)=>n+Number(x.split(":")[1]),0),9627);assert.ok(assignmentWrites.every(x=>Number(x.split(":")[1])<=ASSIGNMENT_CHUNK_SIZE));assert.equal(assignmentWrites.reduce((n,x)=>n+Number(x.split(":")[1]),0),9627);assert.equal(r.writes.at(-1),"audit");assert.deepEqual(f.source,before);});
test("later chunk and audit failures roll back all target writes",async()=>{for(const options of [{failAreaChunk:3},{failAssignmentChunk:2},{failAudit:true}]){const f=fixture(),r=repoFor(f,options);await assert.rejects(()=>runCampaignGeographyBackfill({repository:r.repository,expectedIdentity:expected,mode:"execute",confirmation:CAMPAIGN_GEOGRAPHY_EXECUTION_CONFIRMATION}));assert.deepEqual(r.target,{levels:[],areas:[],assignments:[]});}});
test("Production is prohibited and errors/output contain no connection secret",async()=>{const f=fixture(),r=repoFor(f);r.repository.getIdentity=async()=>({database:"neondb",branchId:"br-noisy-forest-axlven4c"});await assert.rejects(()=>runCampaignGeographyBackfill({repository:r.repository,expectedIdentity:{...expected,branchId:"br-noisy-forest-axlven4c"}}),{code:"PRODUCTION_PROHIBITED"});assert.doesNotMatch(JSON.stringify(r.writes),/postgresql:|password|token/i);});
test("identity report distinguishes database-verified values from operator labels",()=>{assert.deepEqual(assertSafeIdentity({database:"neondb",branchId:"br-test"},expected),{databaseVerified:{database:"neondb",branchId:"br-test"},operatorExpected:{projectId:"project",branchName:"test"}});assert.throws(()=>assertSafeIdentity({database:"neondb",branchId:"br-other"},expected),{code:"IDENTITY_MISMATCH"});assert.throws(()=>assertSafeIdentity({database:"neondb",branchId:"br-noisy-forest-axlven4c"},{...expected,branchId:"br-noisy-forest-axlven4c"}),{code:"PRODUCTION_PROHIBITED"});});
test("strict CLI parsing defaults safely and rejects unknown, duplicate, and malformed arguments",()=>{assert.deepEqual(parseBackfillCliArgs([]),{mode:"dry-run",confirmation:undefined});assert.deepEqual(parseBackfillCliArgs(["--dry-run"]),{mode:"dry-run",confirmation:undefined});assert.throws(()=>parseBackfillCliArgs(["--wat"]),{code:"CLI_UNKNOWN_ARGUMENT"});assert.throws(()=>parseBackfillCliArgs(["value"]),{code:"CLI_UNKNOWN_ARGUMENT"});assert.throws(()=>parseBackfillCliArgs(["--dry-run","--execute"]),{code:"CLI_AMBIGUOUS_MODE"});assert.throws(()=>parseBackfillCliArgs(["--execute","--confirm=bad\nvalue"]),{code:"CLI_MALFORMED_CONFIRMATION"});assert.deepEqual(parseBackfillCliArgs(["--execute",`--confirm=${CAMPAIGN_GEOGRAPHY_EXECUTION_CONFIRMATION}`]),{mode:"execute",confirmation:CAMPAIGN_GEOGRAPHY_EXECUTION_CONFIRMATION});});
test("invalid CLI exits nonzero with sanitized output before database construction",()=>{const secret="postgresql://operator:do-not-print@example.invalid/neondb?token=secret";const result=spawnSync(process.execPath,["scripts/backfill-campaign-geography.mjs","--unknown"],{cwd:process.cwd(),encoding:"utf8",env:{...process.env,MIGRATION_DATABASE_URL:secret,POLISMART_NEON_PROJECT_ID:"project",POLISMART_NEON_BRANCH_ID:"br-test",POLISMART_NEON_BRANCH_NAME:"test",POLISMART_DATABASE_NAME:"neondb"}});assert.notEqual(result.status,0);const output=`${result.stdout}${result.stderr}`;assert.doesNotMatch(output,/do-not-print|token=secret|postgresql:\/\//u);assert.match(output,/CLI_UNKNOWN_ARGUMENT|Unknown command option/u);});
test("canonical v1 hashing normalizes Unicode, ordering, dates, and distinguishes null and empty",()=>{assert.equal(CAMPAIGN_GEOGRAPHY_CANONICAL_VERSION,"campaign-geography-backfill-canonical-v1");assert.equal(canonicalHash([{name:"é",when:new Date("2026-01-01T00:00:00Z"),value:null}]),canonicalHash([{value:null,when:"2026-01-01T00:00:00.000Z",name:"e\u0301"}]));assert.equal(canonicalHash([{a:1},{a:2}]),canonicalHash([{a:2},{a:1}]));assert.notEqual(canonicalHash([{value:null}]),canonicalHash([{value:""}]));assert.notEqual(canonicalHash([{value:"a"}]),canonicalHash([{value:"b"}]));});
test("canonical row ordering uses locale-independent code-unit order",()=>{const rows=[{value:"ä"},{value:"a"},{value:"Z"},{value:"A"},{value:"e\u0301"},{value:"é"}];const normalizedSorted=[{value:"A"},{value:"Z"},{value:"a"},{value:"ä"},{value:"é"},{value:"é"}];const serialized=`${CAMPAIGN_GEOGRAPHY_CANONICAL_VERSION}\n${JSON.stringify(normalizedSorted)}\n`;const expectedHash=createHash("sha256").update(serialized,"utf8").digest("hex");assert.equal(canonicalHash(rows),expectedHash);assert.equal(canonicalHash(rows),canonicalHash([...rows].reverse()));});
test("UUIDv5 matches the RFC 9562 DNS namespace vector",()=>{assert.equal(uuidV5("www.example.com","6ba7b810-9dad-11d1-80b4-00c04fd430c8"),"2ed6657d-e927-568b-95e1-2665a8aea6a2");assert.equal(uuidV5("same"),uuidV5("same"));assert.notEqual(uuidV5("same"),uuidV5("different"));});
test("multi-node cycles and exact provenance changes are rejected or detected",()=>{const f=fixture();const a=f.source.areas[1],b=f.source.areas[7],c=f.source.areas[44];a.parentId=c.id;b.parentId=a.id;c.parentId=b.id;assert.throws(()=>buildCampaignGeographyPlan(f.source,f.actors),{code:"HIERARCHY_CYCLE"});const clean=fixture(),p=buildCampaignGeographyPlan(clean.source,clean.actors),source=clean.source.areas[0],target=p.masterAreas.find(area=>area.id===source.id);for(const field of ["sourceInstitution","sourceDocument","sourceVersionDate","retrievalDate","importedAt","validationStatus","createdAt","updatedAt"])assert.deepEqual(target[field],source[field],field);assert.equal(target.sourceVersionDate,null);const changed=structuredClone(prismaShape({levels:p.masterLevels,areas:p.masterAreas,assignments:p.assignments}));changed.areas[0].sourceDocument="Other";assert.throws(()=>classifyTarget(changed,p),{code:"CONFLICTING_TARGET"});});
