export const AFROBAROMETER_MINIMUM_SAMPLE_SIZE = 100;
export const AFROBAROMETER_INTELLIGENCE_CATEGORIES = Object.freeze([
  "PUBLIC_PRIORITIES",
  "ECONOMIC_CONDITIONS",
  "GOVERNMENT_PERFORMANCE",
  "INSTITUTIONAL_TRUST",
  "DEMOCRACY",
  "GOVERNANCE",
  "CORRUPTION",
  "PUBLIC_SERVICES",
  "SECURITY",
  "CIVIC_PARTICIPATION",
]);
// Source: Afrobarometer, Merged Round 9 codebook (39 countries), 25 June 2024.
// https://www.afrobarometer.org/wp-content/uploads/2024/10/AB_R9.MergeCodebook_25Jun24.final_.pdf
// Add mappings only from this or a later reviewed authoritative codebook. Never infer meaning from values.
const MOST_IMPORTANT_PROBLEM_RESPONSES = Object.freeze({
  0: "Nothing/no problems",
  1: "Management of the economy",
  2: "Wages, incomes, and salaries",
  3: "Unemployment",
  4: "Poverty/Destitution",
  5: "Rates and taxes",
  6: "Loans/Credit",
  7: "Farming/Agriculture",
  8: "Food shortage/Famine",
  9: "Drought",
  10: "Land",
  11: "Transportation",
  12: "Communications",
  13: "Infrastructure/Roads",
  14: "Education",
  15: "Housing",
  16: "Electricity",
  17: "Water supply",
  18: "Orphans/Street children/Homeless children",
  19: "Services (other)",
  20: "Health",
  21: "AIDS",
  22: "Sickness/Disease",
  23: "Crime and security",
  24: "Corruption",
  25: "Political violence",
  26: "Political instability/Political divisions/Ethnic tensions",
  27: "Discrimination/Inequality",
  28: "Gender issues/Women's rights",
  29: "Democracy/Political rights",
  30: "War (international)",
  31: "Civil war",
  32: "Agricultural marketing",
  33: "Climate change",
  34: "COVID-19",
  180: "Internally displaced",
  1500: "Pollution",
  1680: "Drug abuse",
});

export const AFROBAROMETER_COUNTRY_MAPPINGS = Object.freeze({
  2: "Angola",
  3: "Benin",
  4: "Botswana",
  5: "Burkina Faso",
  6: "Cabo Verde",
  7: "Cameroon",
  8: "Congo-Brazzaville",
  9: "Côte d'Ivoire",
  10: "Eswatini",
  11: "Ethiopia",
  12: "Gabon",
  13: "The Gambia",
  14: "Ghana",
  15: "Guinea",
  16: "Kenya",
  17: "Lesotho",
  18: "Liberia",
  19: "Madagascar",
  20: "Malawi",
  21: "Mali",
  22: "Mauritania",
  23: "Mauritius",
  24: "Morocco",
  25: "Mozambique",
  26: "Namibia",
  27: "Niger",
  28: "Nigeria",
  29: "São Tomé and Príncipe",
  30: "Senegal",
  31: "Seychelles",
  32: "Sierra Leone",
  33: "South Africa",
  34: "Sudan",
  35: "Tanzania",
  36: "Togo",
  37: "Tunisia",
  38: "Uganda",
  39: "Zambia",
  40: "Zimbabwe",
});

export const AFROBAROMETER_INDICATOR_MAPPINGS = Object.freeze([
  Object.freeze({
    questionCode: "Q45PT1",
    questionText:
      "In your opinion, what are the most important problems facing this country that government should address?",
    indicatorCode: "PUBLIC_PRIORITY_FIRST_RESPONSE",
    indicatorName: "Most important public problem - first response",
    category: "PUBLIC_PRIORITIES",
    responseMapping: MOST_IMPORTANT_PROBLEM_RESPONSES,
  }),
]);
export const AFROBAROMETER_MAPPING_VERSION = "r9-merged-codebook-2024-06-25-v1";
