const policy = (tablePrivileges = [], updateColumns = []) =>
  Object.freeze({
    tablePrivileges: Object.freeze([...tablePrivileges]),
    updateColumns: Object.freeze([...updateColumns]),
  });

export const RUNTIME_DATABASE_PRIVILEGES = Object.freeze({
  User: policy(),
  WorkflowModule: policy(),
  AgentRun: policy(),
  AgentStep: policy(),
  ReviewCase: policy(),
  ReadinessCheck: policy(),
  ReadinessQuestion: policy(),
  ReadinessSubmission: policy(),
  AuditEvent: policy(),
  auth_users: policy(["SELECT", "INSERT"], ["password_hash", "email_verified_at", "updated_at"]),
  organizations: policy(["SELECT", "INSERT"]),
  campaigns: policy(
    ["SELECT", "INSERT"],
    ["name", "country", "election_type", "status", "starts_at", "ends_at", "updated_at"],
  ),
  memberships: policy(["SELECT", "INSERT"], ["role", "status", "updated_at"]),
  permissions: policy(),
  role_permissions: policy(),
  auth_sessions: policy(["SELECT", "INSERT", "DELETE"]),
  email_verification_tokens: policy(["SELECT", "INSERT", "DELETE"], ["used_at", "updated_at"]),
  password_reset_tokens: policy(["SELECT", "INSERT", "DELETE"], ["used_at", "updated_at"]),
  security_audit_events: policy(["SELECT", "INSERT"]),
  campaign_leaders: policy(["SELECT", "INSERT"]),
  initiatives: policy(
    ["SELECT", "INSERT"],
    ["title", "description", "owner_id", "priority", "status", "due_at", "updated_at"],
  ),
  activities: policy(
    ["SELECT", "INSERT"],
    ["title", "description", "owner_id", "priority", "status", "due_at", "updated_at"],
  ),
  campaign_tasks: policy(
    ["SELECT", "INSERT"],
    ["title", "description", "owner_id", "priority", "status", "due_at", "updated_at"],
  ),
  task_dependencies: policy(["SELECT", "INSERT"]),
  geographic_levels: policy(
    ["SELECT", "INSERT"],
    ["name", "order_index", "is_active", "updated_at"],
  ),
  geographic_areas: policy(
    ["SELECT", "INSERT"],
    ["level_id", "parent_id", "name", "code", "is_active", "updated_at"],
  ),
  campaign_events: policy(["SELECT", "INSERT"]),
  volunteers: policy(
    ["SELECT", "INSERT"],
    [
      "contact_authorized",
      "email",
      "phone",
      "availability",
      "languages",
      "skills",
      "training_status",
      "updated_at",
    ],
  ),
  volunteer_assignments: policy(["SELECT", "INSERT"]),
  event_participation: policy(["SELECT", "INSERT"]),
  knowledge_documents: policy(
    ["SELECT", "INSERT", "DELETE"],
    ["extracted_text", "processing_status", "processing_error", "approval_status", "updated_at"],
  ),
  knowledge_chunks: policy(["SELECT", "INSERT"]),
  data_sources: policy(["SELECT"]),
  survey_imports: policy(["SELECT"]),
  survey_questions: policy(),
  survey_countries: policy(["SELECT"]),
  survey_regions: policy(),
  survey_indicator_definitions: policy(["SELECT"]),
  survey_indicator_values: policy(),
  survey_aggregate_results: policy(["SELECT"]),
  ai_conversations: policy(["SELECT", "INSERT"]),
  ai_messages: policy(["SELECT", "INSERT"]),
  ai_feedback: policy(["SELECT", "INSERT"], ["type", "note", "updated_at"]),
  policy_cases: policy(["SELECT", "INSERT"], ["status", "updated_at"]),
  policy_evidence: policy(["SELECT", "INSERT"]),
  policy_options: policy(["SELECT", "INSERT"]),
  policy_revisions: policy(["SELECT", "INSERT"]),
  policy_approvals: policy(["SELECT", "INSERT"]),
  media_items: policy(
    ["SELECT", "INSERT"],
    [
      "campaign_id",
      "headline",
      "publisher",
      "published_at",
      "topic",
      "geography",
      "source",
      "source_url",
      "summary",
      "aggregate_sentiment",
      "updated_at",
    ],
  ),
  communications: policy(["SELECT", "INSERT"], ["status", "updated_at"]),
  communication_revisions: policy(["SELECT", "INSERT"]),
  communication_approvals: policy(["SELECT", "INSERT"]),
  ai_provider_records: policy(["SELECT", "INSERT"], ["is_active", "updated_at"]),
  prompt_template_versions: policy(["SELECT", "INSERT"]),
  ai_usage_logs: policy(["SELECT", "INSERT"]),
  ai_error_reports: policy(["SELECT", "INSERT"]),
  fundraising_goals: policy(),
  fundraising_contacts: policy(),
  fundraising_contributions: policy(),
  fundraising_activities: policy(),
  fundraising_follow_ups: policy(),
  fundraising_history: policy(),
  prelaunch_leads: policy(["SELECT", "INSERT"], ["status", "updated_at"]),
  prelaunch_lead_follow_ups: policy(["SELECT", "INSERT"], ["completed_at", "completed_by_id"]),
});

export const RUNTIME_SEQUENCE_PRIVILEGES = Object.freeze({});
