CREATE TYPE "PolicyWorkflowStatus" AS ENUM ('PROBLEM','EVIDENCE','RESEARCH','OPTIONS','AI_DRAFT','HUMAN_REVIEW','APPROVED','REJECTED');
CREATE TYPE "CommunicationType" AS ENUM ('SPEECH','PRESS_RELEASE','POLICY_EXPLANATION','ANNOUNCEMENT','NEWSLETTER','FAQ');
CREATE TYPE "CommunicationStatus" AS ENUM ('DRAFT','AI_ASSISTED','HUMAN_REVIEW','COMPLIANCE_REVIEW','APPROVED','REJECTED');
CREATE TYPE "ReviewDecision" AS ENUM ('APPROVED','REJECTED','CHANGES_REQUESTED');
CREATE TYPE "AggregateSentiment" AS ENUM ('POSITIVE','NEUTRAL','NEGATIVE','MIXED','UNKNOWN');

CREATE TABLE "policy_cases" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"campaign_id" UUID NOT NULL,"created_by_id" UUID NOT NULL,"title" TEXT NOT NULL,"problem" TEXT NOT NULL,"status" "PolicyWorkflowStatus" NOT NULL DEFAULT 'PROBLEM',"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "policy_cases_pkey" PRIMARY KEY("id"));
CREATE TABLE "policy_evidence" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"policy_case_id" UUID NOT NULL,"evidence_type" TEXT NOT NULL,"title" TEXT NOT NULL,"source" TEXT NOT NULL,"source_url" TEXT,"summary" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "policy_evidence_pkey" PRIMARY KEY("id"));
CREATE TABLE "policy_options" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"policy_case_id" UUID NOT NULL,"title" TEXT NOT NULL,"description" TEXT NOT NULL,"tradeoffs" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "policy_options_pkey" PRIMARY KEY("id"));
CREATE TABLE "policy_revisions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"policy_case_id" UUID NOT NULL,"author_id" UUID NOT NULL,"version" INTEGER NOT NULL,"content" TEXT NOT NULL,"is_ai_generated" BOOLEAN NOT NULL DEFAULT false,"disclaimer" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "policy_revisions_pkey" PRIMARY KEY("id"));
CREATE TABLE "policy_approvals" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"policy_case_id" UUID NOT NULL,"reviewer_id" UUID NOT NULL,"decision" "ReviewDecision" NOT NULL,"note" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "policy_approvals_pkey" PRIMARY KEY("id"));
CREATE TABLE "media_items" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"campaign_id" UUID NOT NULL,"headline" TEXT NOT NULL,"publisher" TEXT NOT NULL,"published_at" TIMESTAMP(3) NOT NULL,"topic" TEXT NOT NULL,"geography" TEXT NOT NULL,"source" TEXT NOT NULL,"source_url" TEXT NOT NULL,"summary" TEXT NOT NULL,"aggregate_sentiment" "AggregateSentiment" NOT NULL DEFAULT 'UNKNOWN',"integration_key" TEXT NOT NULL,"external_id" TEXT NOT NULL,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "media_items_pkey" PRIMARY KEY("id"));
CREATE TABLE "communications" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"campaign_id" UUID NOT NULL,"created_by_id" UUID NOT NULL,"title" TEXT NOT NULL,"type" "CommunicationType" NOT NULL,"status" "CommunicationStatus" NOT NULL DEFAULT 'DRAFT',"compliance_required" BOOLEAN NOT NULL DEFAULT false,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "communications_pkey" PRIMARY KEY("id"));
CREATE TABLE "communication_revisions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"communication_id" UUID NOT NULL,"author_id" UUID NOT NULL,"version" INTEGER NOT NULL,"content" TEXT NOT NULL,"is_ai_generated" BOOLEAN NOT NULL DEFAULT false,"disclaimer" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "communication_revisions_pkey" PRIMARY KEY("id"));
CREATE TABLE "communication_approvals" ("id" UUID NOT NULL DEFAULT gen_random_uuid(),"tenant_id" UUID NOT NULL,"communication_id" UUID NOT NULL,"reviewer_id" UUID NOT NULL,"stage" TEXT NOT NULL,"decision" "ReviewDecision" NOT NULL,"note" TEXT,"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL,CONSTRAINT "communication_approvals_pkey" PRIMARY KEY("id"));

CREATE UNIQUE INDEX "policy_revisions_policy_case_id_version_key" ON "policy_revisions"("policy_case_id","version"); CREATE INDEX "policy_cases_tenant_id_campaign_id_status_updated_at_idx" ON "policy_cases"("tenant_id","campaign_id","status","updated_at"); CREATE INDEX "policy_evidence_tenant_id_policy_case_id_idx" ON "policy_evidence"("tenant_id","policy_case_id"); CREATE INDEX "policy_options_tenant_id_policy_case_id_idx" ON "policy_options"("tenant_id","policy_case_id"); CREATE INDEX "policy_revisions_tenant_id_policy_case_id_created_at_idx" ON "policy_revisions"("tenant_id","policy_case_id","created_at"); CREATE INDEX "policy_approvals_tenant_id_policy_case_id_created_at_idx" ON "policy_approvals"("tenant_id","policy_case_id","created_at");
CREATE UNIQUE INDEX "media_items_tenant_id_integration_key_external_id_key" ON "media_items"("tenant_id","integration_key","external_id"); CREATE INDEX "media_items_tenant_id_campaign_id_published_at_idx" ON "media_items"("tenant_id","campaign_id","published_at"); CREATE INDEX "media_items_tenant_id_campaign_id_topic_geography_idx" ON "media_items"("tenant_id","campaign_id","topic","geography");
CREATE UNIQUE INDEX "communication_revisions_communication_id_version_key" ON "communication_revisions"("communication_id","version"); CREATE INDEX "communications_tenant_id_campaign_id_status_updated_at_idx" ON "communications"("tenant_id","campaign_id","status","updated_at"); CREATE INDEX "communication_revisions_tenant_id_communication_id_created_at_idx" ON "communication_revisions"("tenant_id","communication_id","created_at"); CREATE INDEX "communication_approvals_tenant_id_communication_id_stage_created_at_idx" ON "communication_approvals"("tenant_id","communication_id","stage","created_at");
ALTER TABLE "policy_cases" ADD CONSTRAINT "policy_cases_campaign_id_fkey" FOREIGN KEY("campaign_id") REFERENCES "campaigns"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "policy_evidence" ADD CONSTRAINT "policy_evidence_policy_case_id_fkey" FOREIGN KEY("policy_case_id") REFERENCES "policy_cases"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "policy_options" ADD CONSTRAINT "policy_options_policy_case_id_fkey" FOREIGN KEY("policy_case_id") REFERENCES "policy_cases"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "policy_revisions" ADD CONSTRAINT "policy_revisions_policy_case_id_fkey" FOREIGN KEY("policy_case_id") REFERENCES "policy_cases"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "policy_approvals" ADD CONSTRAINT "policy_approvals_policy_case_id_fkey" FOREIGN KEY("policy_case_id") REFERENCES "policy_cases"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "media_items" ADD CONSTRAINT "media_items_campaign_id_fkey" FOREIGN KEY("campaign_id") REFERENCES "campaigns"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "communications" ADD CONSTRAINT "communications_campaign_id_fkey" FOREIGN KEY("campaign_id") REFERENCES "campaigns"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "communication_revisions" ADD CONSTRAINT "communication_revisions_communication_id_fkey" FOREIGN KEY("communication_id") REFERENCES "communications"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "communication_approvals" ADD CONSTRAINT "communication_approvals_communication_id_fkey" FOREIGN KEY("communication_id") REFERENCES "communications"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "policy_cases" ADD CONSTRAINT "policy_cases_created_by_id_fkey" FOREIGN KEY("created_by_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "policy_revisions" ADD CONSTRAINT "policy_revisions_author_id_fkey" FOREIGN KEY("author_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "policy_approvals" ADD CONSTRAINT "policy_approvals_reviewer_id_fkey" FOREIGN KEY("reviewer_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "communications" ADD CONSTRAINT "communications_created_by_id_fkey" FOREIGN KEY("created_by_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "communication_revisions" ADD CONSTRAINT "communication_revisions_author_id_fkey" FOREIGN KEY("author_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "communication_approvals" ADD CONSTRAINT "communication_approvals_reviewer_id_fkey" FOREIGN KEY("reviewer_id") REFERENCES "auth_users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
